version: '2'
services:

 st-user-mongodb:
  container_name: st-user-mongodb
  image: mongo
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: example
  ports:
   - "27017:27017"
  entrypoint: mongod --bind_ip_all
#  command: mongod --logpath=/dev/null # --quiet

 user:
  build: .
  ports:
   - "8080:8080"
   - "8443:8443"
  environment:
   SPRING_PROFILES_ACTIVE: uat
   DATABASE: st-user-db
   MONGODB_HOST: st-user-mongodb
   MONGODB_PORT: 27017
  links:
   - st-user-mongodb
